/**:
  ros__parameters:
    # PID gains
    kp: 1.0
    ki: 0.1
    kd: 0.01

    # Feedforward gain
    kff: 1.0

    # Cuttoff frequency for feedforward filter term
    setpoint_filter_cutoff_frequency_hz: 0.1

    # Cutoff frequency for derivative term
    derivative_filter_cutoff_frequency_hz: 0.01

    # Velocity limits
    max_velocity_mps: 2.0
    min_velocity_mps: -2.0

    # Node and controller frequency
    control_frequency: 20.0
